<fildset>
    <legend>FORMULARIO DE MANUTENÇÃO</legend>
    <div class="col-xs-12">
        <div class="x_panel">
            <div class="x_content">
                <!-- Smart Wizard -->
                <div class="row">
                    <div class="col-md-10 col-xs-12 col-md-offset-1 col-xs-offset-0">
                        <div id="wizard" class="form_wizard wizard_horizontal">
                            <?php echo $this->partial('/admin/admin/tpl/vendas/step');?>

                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-8 col-sm-10 col-xs-12 col-md-offset-2 col-sm-offset-1 col-xs-offset-0">
                        <fieldset>
                            <legend>SUB TOTAIS DO PEDIDO</legend>
                            <div class="row">
                                <div class="col-md-3 col-xs-12">
                                    <div class="form-group">
                                        <label class="control-label" for="pago"> <?php echo $this->translate('{{pago}}');?>  </label>
                                        #pago#
                                    </div>
                                </div>
                                <div class="col-md-3 col-xs-12">
                                    <div class="form-group">
                                        <label class="control-label" for="desconto"> <?php echo $this->translate('{{desconto}}');?>  </label>
                                        #desconto#
                                    </div>
                                </div>
                                <div class="col-md-3 col-xs-12">
                                    <div class="form-group">
                                        <label class="control-label" for="juros"> <?php echo $this->translate('{{juros}}');?>  </label>
                                        #juros#
                                    </div>
                                </div>
                                <div class="col-md-3 col-xs-12">
                                    <div class="form-group">
                                        <label class="control-label" for="valor"> <?php echo $this->translate('{{valor}}');?>  </label>
                                        #valor#
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                    </div>
                </div>

                <div class="box-footer">
                    <div class="pull-right">
                        #btn-voltar#
                    </div>
                </div>
                <!-- End SmartWizard Content -->
            </div>
        </div>
</fildset>
<script>
    $(document).ready(function () {
      $(".cabecalho").change(function(){
       var data={
              id:		      $("#id").val(),
              codigo: 		  $("#codigo").val(),
              empresa:        $("#empresa").val(),
              asset_id:       $("#asset_id").val(),
              tipo:           $("#tipo").val(),
              created_by:     $("#created_by").val(),
              cliente_id:     $("#cliente_id").val(),
              fpgto:          $("#fpgto").val(),
              cpgto:          $("#cpgto").val(),
              desconto:       $("#desconto").val(),
              juros:          $("#juros").val(),
              pago:           $("#pago").val(),
              valor:          $("#valor").val(),
              description:    $("#description").val(),
              state:          $("#state").val(),
              access:         $("#access").val(),
              created:        $("#created").val(),
              modified:       $("#modified").val()
       };
          $.ajax({
              url:'/vendas/add',
              type:'post',
              datatype:'json',
              data:data,
              success:function(result){
                  console.log(result);
              }
          })

      });
    })

</script>
