<div class="row">
    <div class="col-md-2 col-sm-4 col-xs-12">
        <div class="form-group">
            <div style="margin-top: 20px;">#tipo#</div>
        </div>
    </div>
    <div class="col-lg-2 col-md-3 col-sm-4 col-xs-12">
        <div class="form-group">
            <label for=""> <?php echo $this->translate('{{codigo}}');?></label>
            #codigo#
        </div>
    </div>
    <div class="col-lg-2 col-md-3 col-sm-4 col-xs-12">
        <div class="form-group">
            <label for=""> <?php echo $this->translate('{{created}}');?></label>
            <div class="col-xs-12 xdisplay_inputx form-group has-feedback">
                #created#<span class="fa fa-calendar-o form-control-feedback right"></span></div>
        </div>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <div class="form-group">
            <label for=""> <?php echo $this->translate('{{cpgto}}');?></label>
            #cpgto#
        </div>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <div class="form-group">
            <label for=""> <?php echo $this->translate('{{fpgto}}');?></label>
            #fpgto#
        </div>
    </div>
</div>

<div class="row">

    <div class="col-md-4 col-sm-12">
        <div class="form-group">
            <label for=""> <?php echo $this->translate('{{cliente_id}}');?></label>
            #cliente_id#
        </div>
    </div>
    <div class="col-md-2 col-sm-3 col-xs-12">
        <div class="form-group">
            <label for=""> <?php echo $this->translate('{{pago}}');?></label>
            #pago#
        </div>
    </div>
    <div class="col-md-2 col-sm-3 col-xs-12">
        <div class="form-group">
            <label for=""> <?php echo $this->translate('{{desconto}}');?></label>
            #desconto#
        </div>
    </div>
    <div class="col-md-2 col-sm-3 col-xs-12">
        <div class="form-group">
            <label for=""> <?php echo $this->translate('{{juros}}');?></label>
            #juros#
        </div>
    </div>
    <div class="col-md-2 col-sm-3 col-xs-12">
        <div class="form-group">
            <label for=""> <?php echo $this->translate('{{valor}}');?></label>
            #valor#
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <table class="table table-condensed table-hover">
            <thead>
            <tr>
                <th>CODIGO</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>01</td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="form-group">
            <label for=""> <?php echo $this->translate('{{description}}');?></label>
            #description#
        </div>
    </div>
</div>
