<div id="step-3">
    <div class="row">
        <div class="col-md-8 col-xs-12 col-md-offset-2 col-xs-offset-0">
            <div data-toggle="buttons" class="btn-group">
                <label class="btn btn-default active">
                   <input type="radio" id="avista" name="fpgto">  <span class="fa fa-money fa-3x"></span>
                </label>
                <label class="btn btn-default">
                    <input type="radio" id="paypal" name="fpgto">  <span class="fa fa-cc-paypal fa-3x"></span>
                </label>
                <label class="btn btn-default">
                    <input type="radio" id="barcode" name="fpgto">  <span class="fa fa-barcode fa-3x"></span>
                </label>
            </div>
        </div>
    </div>
    <div class="row">
    	<div class="col-xs-12  col-md-8 col-xs-offset-0 col-md-offset-2" id="pagamentos">
            <div data-toggle="buttons" class="btn-group">
                #situacao#
            </div>
    	</div>
    </div>
     <div class="row">
    	<div class="col-xs-12  col-md-8 col-xs-offset-0 col-md-offset-2" id="pagamentos">
               <h2>SELECIONE A FORMA DE PAGAMENTO</h2>
    	</div>
    </div>

</div>
